"""
Generate Python constants from the canonical LuaSkills package-configuration contract.
从规范 LuaSkills 技能包配置契约生成 Python 常量。
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

# Repository root containing the canonical contract and generated module.
# 包含规范契约与生成模块的仓库根目录。
REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
# Canonical contract copied from the matching LuaSkills core release.
# 从匹配 LuaSkills 核心版本复制的规范契约。
CONTRACT_PATH = (
    REPOSITORY_ROOT / "contracts" / "skill-config" / "v1" / "contract.json"
)
# Generated Python module consumed by the public package.
# 公共包使用的已生成 Python 模块。
OUTPUT_PATH = REPOSITORY_ROOT / "src" / "luaskills" / "config_contract.py"


def render_tuple(values: list[str]) -> str:
    """
    Render one canonical string list as an indented Python tuple body.
    把一个规范字符串列表渲染为缩进的 Python 元组主体。

    Args:
        values: Canonically ordered string values.
    Returns:
        Indented tuple member source.

    参数：
        values：按规范排序的字符串值。
    返回：
        缩进后的元组成员源码。
    """

    return "\n".join(f"    {value!r}," for value in values)


def generate_source(contract: dict[str, Any]) -> str:
    """
    Render deterministic Python constants from one canonical contract.
    从一个规范契约渲染确定性 Python 常量。

    Args:
        contract: Parsed canonical contract.
    Returns:
        Complete generated Python source.

    参数：
        contract：已解析规范契约。
    返回：
        完整的已生成 Python 源码。
    """

    # Declaration arrays preserve the canonical core-generated order.
    # 声明数组保持核心生成的规范顺序。
    types = render_tuple(contract["declaration"]["types"])
    formats = render_tuple(contract["declaration"]["formats"])
    states = render_tuple(contract["declaration"]["states"])
    # Discovery modes and store scopes preserve canonical order.
    # 发现模式与存储作用域保持规范顺序。
    describe_modes = render_tuple(contract["declaration"]["describe_modes"])
    store_scopes = render_tuple(contract["declaration"]["store_scopes"])
    # Error codes preserve the canonical core-generated order.
    # 错误码保持核心生成的规范顺序。
    errors = render_tuple(contract["errors"])
    return f'''"""
Runtime constants generated from the core package-configuration contract.
从核心技能包配置契约生成的运行时常量。
"""

from __future__ import annotations

from typing import Literal, TypeAlias

# Code generated by scripts/generate_skill_config_contract.py; do not edit.
# 此文件由 scripts/generate_skill_config_contract.py 生成；请勿手工编辑。

# Version of the package-configuration wire contract.
# 技能包配置线协议版本。
SKILL_CONFIG_CONTRACT_VERSION = {contract["contract_version"]}

# Stable declared scalar types.
# 稳定的已声明标量类型。
SKILL_PACKAGE_CONFIG_TYPES = (
{types}
)

# Stable host rendering formats.
# 稳定的宿主渲染格式。
SKILL_PACKAGE_CONFIG_FORMATS = (
{formats}
)

# Stable effective-value states.
# 稳定的有效值状态。
SKILL_PACKAGE_CONFIG_STATES = (
{states}
)

# Stable package-configuration discovery modes.
# 稳定的技能包配置发现模式。
SKILL_PACKAGE_CONFIG_DESCRIBE_MODES = (
{describe_modes}
)

# Stable package-configuration store scopes.
# 稳定的技能包配置存储作用域。
SKILL_CONFIG_STORE_SCOPES = (
{store_scopes}
)

# Stable machine-readable package-configuration error codes.
# 稳定的机器可读技能包配置错误码。
SKILL_CONFIG_ERROR_CODES = (
{errors}
)

# Largest exactly representable integer shared by every supported SDK.
# 所有受支持 SDK 共同精确表示的最大整数。
SKILL_CONFIG_MAXIMUM_SAFE_INTEGER = {contract["limits"]["maximum_safe_integer"]:_}

# Largest event page accepted by the core contract.
# 核心契约允许的最大事件分页大小。
SKILL_CONFIG_MAXIMUM_EVENT_POLL_LIMIT = {contract["limits"]["maximum_event_poll_limit"]:_}

# Static type of one declared package-configuration scalar.
# 单个已声明技能包配置标量的静态类型。
SkillPackageConfigType: TypeAlias = Literal[{", ".join(repr(value) for value in contract["declaration"]["types"])}]

# Static type of one optional host rendering format.
# 单个可选宿主渲染格式的静态类型。
SkillPackageConfigFormat: TypeAlias = Literal[{", ".join(repr(value) for value in contract["declaration"]["formats"])}]

# Static type of one unambiguous effective-value state.
# 单个无歧义有效值状态的静态类型。
SkillPackageConfigItemState: TypeAlias = Literal[{", ".join(repr(value) for value in contract["declaration"]["states"])}]

# Static type of one package-configuration discovery mode.
# 单个技能包配置发现模式的静态类型。
SkillPackageConfigDescribeMode: TypeAlias = Literal[{", ".join(repr(value) for value in contract["declaration"]["describe_modes"])}]

# Static type of one package-configuration store scope.
# 单个技能包配置存储作用域的静态类型。
SkillConfigStoreScope: TypeAlias = Literal[{", ".join(repr(value) for value in contract["declaration"]["store_scopes"])}]

# Static type of one stable package-configuration error code.
# 单个稳定技能包配置错误码的静态类型。
SkillConfigErrorCode: TypeAlias = Literal[{", ".join(repr(value) for value in contract["errors"])}]
'''


def main() -> None:
    """
    Generate the module or verify that the checked-in output is current.
    生成模块或验证已检入输出为最新状态。

    Returns:
        None.
    返回：
        无。
    """

    # Parsed canonical contract is the sole source for generated values.
    # 已解析规范契约是生成值的唯一来源。
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    # Expected source is rendered deterministically for generation and checking.
    # 预期源码以确定性方式渲染，供生成与检查共同使用。
    expected = generate_source(contract)
    if "--check" in sys.argv[1:]:
        # Existing source is compared exactly without whitespace normalization.
        # 现有源码不做空白规范化而进行精确比较。
        existing = OUTPUT_PATH.read_text(encoding="utf-8")
        if existing != expected:
            raise SystemExit(
                "src/luaskills/config_contract.py is stale; "
                "run python scripts/generate_skill_config_contract.py"
            )
        return
    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
