"""
Runtime constants generated from the core package-configuration contract.
从核心技能包配置契约生成的运行时常量。
"""

from __future__ import annotations

from typing import Literal, TypeAlias

# Code generated by scripts/generate_skill_config_contract.py; do not edit.
# 此文件由 scripts/generate_skill_config_contract.py 生成；请勿手工编辑。

# Version of the package-configuration wire contract.
# 技能包配置线协议版本。
SKILL_CONFIG_CONTRACT_VERSION = 1

# Stable declared scalar types.
# 稳定的已声明标量类型。
SKILL_PACKAGE_CONFIG_TYPES = (
    'integer',
    'string',
    'float',
    'enum',
    'boolean',
)

# Stable host rendering formats.
# 稳定的宿主渲染格式。
SKILL_PACKAGE_CONFIG_FORMATS = (
    'text',
    'password',
    'uri',
    'path',
    'file',
    'directory',
    'multiline',
)

# Stable effective-value states.
# 稳定的有效值状态。
SKILL_PACKAGE_CONFIG_STATES = (
    'unset',
    'missing',
    'default',
    'configured',
    'invalid',
)

# Stable package-configuration discovery modes.
# 稳定的技能包配置发现模式。
SKILL_PACKAGE_CONFIG_DESCRIBE_MODES = (
    'effective',
    'installed',
)

# Stable package-configuration store scopes.
# 稳定的技能包配置存储作用域。
SKILL_CONFIG_STORE_SCOPES = (
    'skills',
    'system-skills',
)

# Stable machine-readable package-configuration error codes.
# 稳定的机器可读技能包配置错误码。
SKILL_CONFIG_ERROR_CODES = (
    'CONFIG_ATOMIC_REPLACE_FAILED',
    'CONFIG_BATCH_ARGUMENT_CONFLICT',
    'CONFIG_BATCH_EMPTY',
    'CONFIG_BATCH_TOO_LARGE',
    'CONFIG_DECLARATION_INVALID',
    'CONFIG_ENUM_VALUE_INVALID',
    'CONFIG_EVENT_CURSOR_EXPIRED',
    'CONFIG_EVENT_CURSOR_INVALID',
    'CONFIG_FILE_TOO_LARGE',
    'CONFIG_FORMAT_INVALID',
    'CONFIG_FORMAT_VERSION_UNSUPPORTED',
    'CONFIG_KEY_INVALID',
    'CONFIG_KEY_UNDECLARED',
    'CONFIG_LOCK_FAILED',
    'CONFIG_LOCK_TIMEOUT',
    'CONFIG_PACKAGE_NOT_FOUND',
    'CONFIG_PATH_INVALID',
    'CONFIG_PATH_UNAVAILABLE',
    'CONFIG_RELOAD_FAILED',
    'CONFIG_RESPONSE_TOO_LARGE',
    'CONFIG_REVISION_CONFLICT',
    'CONFIG_REVISION_EXHAUSTED',
    'CONFIG_REVISION_INVALID',
    'CONFIG_REVISION_REGRESSION',
    'CONFIG_SNAPSHOT_UNAVAILABLE',
    'CONFIG_VALIDATOR_FAILED',
    'CONFIG_VALIDATOR_LIMIT_EXCEEDED',
    'CONFIG_VALIDATOR_TIMEOUT',
    'CONFIG_VALIDATOR_UNAVAILABLE',
    'CONFIG_VALUE_OUT_OF_RANGE',
    'CONFIG_VALUE_TOO_LONG',
    'CONFIG_VALUE_TYPE_INVALID',
    'CONFIG_WATCHER_FAILED',
)

# Largest exactly representable integer shared by every supported SDK.
# 所有受支持 SDK 共同精确表示的最大整数。
SKILL_CONFIG_MAXIMUM_SAFE_INTEGER = 9_007_199_254_740_991

# Largest event page accepted by the core contract.
# 核心契约允许的最大事件分页大小。
SKILL_CONFIG_MAXIMUM_EVENT_POLL_LIMIT = 1_024

# Static type of one declared package-configuration scalar.
# 单个已声明技能包配置标量的静态类型。
SkillPackageConfigType: TypeAlias = Literal['integer', 'string', 'float', 'enum', 'boolean']

# Static type of one optional host rendering format.
# 单个可选宿主渲染格式的静态类型。
SkillPackageConfigFormat: TypeAlias = Literal['text', 'password', 'uri', 'path', 'file', 'directory', 'multiline']

# Static type of one unambiguous effective-value state.
# 单个无歧义有效值状态的静态类型。
SkillPackageConfigItemState: TypeAlias = Literal['unset', 'missing', 'default', 'configured', 'invalid']

# Static type of one package-configuration discovery mode.
# 单个技能包配置发现模式的静态类型。
SkillPackageConfigDescribeMode: TypeAlias = Literal['effective', 'installed']

# Static type of one package-configuration store scope.
# 单个技能包配置存储作用域的静态类型。
SkillConfigStoreScope: TypeAlias = Literal['skills', 'system-skills']

# Static type of one stable package-configuration error code.
# 单个稳定技能包配置错误码的静态类型。
SkillConfigErrorCode: TypeAlias = Literal['CONFIG_ATOMIC_REPLACE_FAILED', 'CONFIG_BATCH_ARGUMENT_CONFLICT', 'CONFIG_BATCH_EMPTY', 'CONFIG_BATCH_TOO_LARGE', 'CONFIG_DECLARATION_INVALID', 'CONFIG_ENUM_VALUE_INVALID', 'CONFIG_EVENT_CURSOR_EXPIRED', 'CONFIG_EVENT_CURSOR_INVALID', 'CONFIG_FILE_TOO_LARGE', 'CONFIG_FORMAT_INVALID', 'CONFIG_FORMAT_VERSION_UNSUPPORTED', 'CONFIG_KEY_INVALID', 'CONFIG_KEY_UNDECLARED', 'CONFIG_LOCK_FAILED', 'CONFIG_LOCK_TIMEOUT', 'CONFIG_PACKAGE_NOT_FOUND', 'CONFIG_PATH_INVALID', 'CONFIG_PATH_UNAVAILABLE', 'CONFIG_RELOAD_FAILED', 'CONFIG_RESPONSE_TOO_LARGE', 'CONFIG_REVISION_CONFLICT', 'CONFIG_REVISION_EXHAUSTED', 'CONFIG_REVISION_INVALID', 'CONFIG_REVISION_REGRESSION', 'CONFIG_SNAPSHOT_UNAVAILABLE', 'CONFIG_VALIDATOR_FAILED', 'CONFIG_VALIDATOR_LIMIT_EXCEEDED', 'CONFIG_VALIDATOR_TIMEOUT', 'CONFIG_VALIDATOR_UNAVAILABLE', 'CONFIG_VALUE_OUT_OF_RANGE', 'CONFIG_VALUE_TOO_LONG', 'CONFIG_VALUE_TYPE_INVALID', 'CONFIG_WATCHER_FAILED']
